import "~/styles/globals.css";

import type {Metadata} from "next";
import {Geist} from "next/font/google";

import {TRPCReactProvider} from "~/trpc/react";
import {TooltipProvider} from "~/components/ui/tooltip";
import {AppSidebar} from "~/components/app-sidebar";
import {SidebarInset, SidebarProvider} from "~/components/ui/sidebar";
import {SiteHeader} from "~/components/site-header";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html className={`${geist.variable}`} lang="en">
        <body>
        <TRPCReactProvider>
            <TooltipProvider>
                <SidebarProvider>
                    <AppSidebar/>
                    <SidebarInset>
                        <SiteHeader/>
                        {children}
                    </SidebarInset>
                </SidebarProvider>
            </TooltipProvider>
        </TRPCReactProvider>
        </body>
        </html>
    );
}
